update docker noteBackend

diff --git a/noteBackend/Dockerfile b/noteBackend/Dockerfile
--- a/noteBackend/Dockerfile
+++ b/noteBackend/Dockerfile
@@ -12,6 +12,8 @@ RUN go install github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen@latest
 RUN oapi-codegen -package=http -generate "types,spec,gin" api/http/note-api.yml > api/http/note-api.gen.go
 RUN go mod tidy
 
+RUN test -f /app/configs/config.yaml || (echo "Config file not found!" && exit 1)
+
 RUN CGO_ENABLED=0 GOOS=linux go build -o /main ./cmd/main.go
 
 FROM scratch
